---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: imap-classifier
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: imap-classifier-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        IMAP_CLASSIFIER_IMAP__USERNAME: "{{ .imap_username }}"
        IMAP_CLASSIFIER_IMAP__PASSWORD: "{{ .imap_password }}"
        IMAP_CLASSIFIER_API__API_KEY: "{{ .api_key }}"
        ANTHROPIC_API_KEY: "{{ .anthropic_api_key }}"
  dataFrom:
    - extract:
        key: IMAP_CLASSIFIER
