---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: actual-oidc-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACTUAL_OPENID_CLIENT_ID: "{{ .client_id }}"
        ACTUAL_OPENID_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: ACTUAL_POCKETID_CLIENT
