---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: komga
spec:
  chartRef:
    kind: OCIRepository
    name: komga
  interval: 30m
  values:
    controllers:
      komga:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gotson/komga
              tag: 1.24.4@sha256:dae630271561b642d47c9723803ec77900d1f0a803fbe6a42da69db5b21ebaeb
            env:
              SERVER_PORT: &port 8080
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /actuator/health
                    port: *port
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /actuator/health
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 15m
                memory: 1Gi
              limits:
                memory: 4Gi
    persistence:
      config:
        existingClaim: komga
      media:
        type: nfs
        server: nas.rtrox.io
        path: /mnt/rusty/media
        globalMounts:
          - path: /data
    route:
      app:
        hostnames:
          - komga.rtrox.io
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    service:
      app:
        controller: komga
        ports:
          http:
            port: *port
