---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./bluesky-pds/ks.yaml
  - ./echo-server/ks.yaml
  - ./grimmory/ks.yaml
  - ./jellyfin/ks.yaml
  - ./komga/ks.yaml
  - ./minecraft-vanilla/ks.yaml
  - ./owncast/ks.yaml
  - ./paperless/ks.yaml
  - ./sure/ks.yaml
  - ./thelounge/ks.yaml
