---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: "grafana-admin-secret"
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .grafana_username }}"
        admin-password: "{{ .grafana_password }}"
        oidc-client-id: "{{ .client_id }}"
        oidc-client-secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: GRAFANA_ADMIN
    - extract:
        key: GRAFANA_POCKETID_CLIENT
