---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ./bambustatus-streamer/ks.yaml
  - ./imap-classifier/ks.yaml
  - ./minecraft-cpw/ks.yaml
  - ./minecraft-sf5/ks.yaml
  - ./paperless/ks.yaml
