{
 "title": "Minecraft (Forge)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "query_result(mc_dimension_chunks_loaded)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(mc_dimension_chunks_loaded)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Servers Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (Mean)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - process_start_time_seconds{job=~\"$job\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time_seconds{job=~\"$job\"} * 1000) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Vendor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_info) by (runtime, vendor, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_info) by (runtime, vendor, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_info) by (runtime, vendor, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_player_list{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Used ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{job=~\"$job\", instance=~\"$instance\", game=\"minecraft\", area=\"heap\"}) by (job, instance)"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_entities_total{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total Loaded Chunks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_dimension_chunks_loaded{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{job=~\"$job\", instance=~\"$instance\", game=\"minecraft\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mc_server_tick_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Tick Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (rate(mc_server_tick_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Entities & Players", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Online Players (Last 5 Minutes)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "last_over_time(mc_player_list{job=~\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "max(mc_player_list{job=~\"$job\"}) by (name, uuid)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top entities by type",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(mc_entities_total{instance=~\"$instance\",job=~\"$job\"}) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top entities by dimension",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(mc_entities_total{instance=~\"$instance\",job=~\"$job\"}) by (dim)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Minecraft Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Overworld Server Tick Speed Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (rate(mc_dimension_tick_seconds_bucket{name=\"overworld\", job=\"$job\"}[5m]))\r\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (rate(mc_dimension_tick_seconds_bucket{name=\"overworld\", job=\"$job\"}[5m]))\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.75,\r\n  sum by (le) (rate(mc_dimension_tick_seconds_bucket{name=\"overworld\", job=\"$job\"}[5m]))\r\n)",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (rate(mc_dimension_tick_seconds_bucket{name=\"overworld\", job=\"$job\"}[5m]))\r\n)",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "TPS by Dimension (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(mc_dimension_tick_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(mc_server_tick_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "P99 Server Tick Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, name) (rate(mc_dimension_tick_seconds_bucket[5m]))\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{job=~\"$job\", instance=~\"$instance\", area=\"heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{job=~\"$job\", instance=~\"$instance\", area=\"heap\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_bytes_committed{job=~\"$job\", instance=~\"$instance\", area=\"heap\"}",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "Non-Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{job=~\"$job\", instance=~\"$instance\", area=\"nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{job=~\"$job\", instance=~\"$instance\", area=\"nonheap\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_bytes_committed{job=~\"$job\", instance=~\"$instance\", area=\"nonheap\"}",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "G1 Eden Space",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Eden Space\", job=~\"$job\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Eden Space\", job=~\"$job\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Eden Space\", job=~\"$job\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Mem Pool: Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\", job=~\"$job\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\", job=~\"$job\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\", job=~\"$job\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Mem Pool: CodeHeap",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_bytes_committed{pool=~\"CodeHeap.*\", job=~\"$job\"})",
       "legendFormat": "Committed"
      },
      {
       "expr": "sum(jvm_memory_pool_bytes_used{pool=~\"CodeHeap.*\", job=~\"$job\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_pool_bytes_committed{pool=~\"CodeHeap.*\", job=~\"$job\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Mem Pool: Compressed Class Space",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\", job=~\"$job\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\", job=~\"$job\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\", job=~\"$job\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Mem Pool: G1 Survivor Space",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Survivor Space\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Survivor Space\", job=~\"$job\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Survivor Space\", job=~\"$job\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Mem Pool: G1 Old Gen",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Old Gen\", job=~\"$job\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Old Gen\", job=~\"$job\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Old Gen\", job=~\"$job\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_threads_current{job=~\"$job\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "jvm_threads_daemon{job=~\"$job\"}",
       "legendFormat": "Daemon"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{job=~\"$job\"}",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "JVM Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 50 },
     "targets": [
      {
       "expr": "jvm_classes_currently_loaded{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_sum{job=~\"$job\"}",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}