---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: sure-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY_BASE: "{{ .secret_key_base }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
  dataFrom:
    - extract:
        key: SURE
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure-minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: sure-minio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GENERIC_S3_ENDPOINT: "http://{{ .endpoint }}"
        GENERIC_S3_BUCKET: "{{ .bucket }}"
        GENERIC_S3_ACCESS_KEY_ID: "{{ .application_key_id }}"
        GENERIC_S3_SECRET_ACCESS_KEY: "{{ .application_key }}"
  dataFrom:
    - extract:
        key: SURE_MINIO_BUCKET
