---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: govee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: govee2mqtt-secret
    template:
      engineVersion: v2
      data:
        GOVEE_API_KEY: "{{ .GOVEE_API_KEY }}"
        GOVEE_MQTT_PASSWORD: "{{ .GOVEE_MQTT_PASSWORD }}"
  data:
    - secretKey: GOVEE_API_KEY
      remoteRef:
        key: GOVEE_API_KEY
    - secretKey: GOVEE_MQTT_PASSWORD
      remoteRef:
        key: GOVEE_MQTT_PASSWORD
