{
 "title": "Minecraft (Fabric)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "query_result(minecraft_entities{job=~\"$job\"})"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_entities)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Servers Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (Mean)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - process_start_time_seconds{job=~\"$job\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "JVM Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_info) by (runtime, vendor, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_info) by (runtime, vendor, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Vendor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_info) by (runtime, vendor, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Used ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{job=~\"$job\", instance=~\"$instance\", game=\"minecraft\", area=\"heap\"}) by (job, instance)"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time_seconds{job=~\"$job\"} * 1000) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{job=~\"$job\", instance=~\"$instance\", game=\"minecraft\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_tps{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_loaded_chunks{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Loaded Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(minecraft_total_loaded_chunks{job=~\"$job\"}) by (world, job))"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}) by (job)"
    }
   ]
  },
  {
   "title": "Minecraft Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Players online",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (world)",
       "legendFormat": "Players in {{world}}"
      }
     ]
    },
    {
     "title": "Loaded chunks",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (world)",
       "legendFormat": "Loaded chunks in {{world}}"
      }
     ]
    },
    {
     "title": "Loaded chunks per 10 minutes",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(minecraft_total_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}[10m]) ",
       "legendFormat": "Loaded chunks in {{world}}"
      }
     ]
    },
    {
     "title": "Ticks Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(minecraft_tps{job=~\"$job\"}) by (job)",
       "legendFormat": "MSPT"
      }
     ]
    },
    {
     "title": "Milliseconds Per Tick",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "MSPT"
      }
     ]
    }
   ]
  },
  {
   "title": "Minecraft Entity Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top entities by type",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Entities by spawn group",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (group)",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Entities by world",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (world)",
       "legendFormat": "Entities in {{world}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=~\"$job\", instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{job=~\"$job\", instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$job\", instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=~\"$job\", instance=~\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{job=~\"$job\", instance=~\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$job\", instance=~\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Eden Space\", job=~\"$job\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Eden Space\", job=~\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Eden Space\", job=~\"$job\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Mem Pool: Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\", job=~\"$job\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\", job=~\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\", job=~\"$job\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Mem Pool: CodeHeap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{pool=~\"CodeHeap.*\", job=~\"$job\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pool=~\"CodeHeap.*\", job=~\"$job\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{pool=~\"CodeHeap.*\", job=~\"$job\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Mem Pool: Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\", job=~\"$job\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\", job=~\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\", job=~\"$job\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Mem Pool: G1 Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Survivor Space\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Survivor Space\", job=~\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Survivor Space\", job=~\"$job\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Mem Pool: G1 Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 29 },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Old Gen\", job=~\"$job\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Old Gen\", job=~\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Old Gen\", job=~\"$job\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=~\"$job\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"$job\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{job=~\"$job\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 34 },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"$job\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}